import Head from "next/head";
import Link from "next/link";
import { getAllPublished } from "../lib/notion";
import styles from "../styles/Home.module.css";
import util from "../styles/util.module.css";

//page header and in-page description
const description = "Blog posts written by me";

export default function Home({ posts }) {
  if (!posts) return <h1>No posts</h1>;
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={util.page} id='aboutPage'>
        <div className={util.pageColumn}>
          <h1 className={util.header}>Blog</h1>
          <p className={util.description}>{description}</p>
          {posts.map((post, index) => (
            <section key={index} className={styles.card}>
              <div>
                <h2>
                  <Link href={`/posts/${post.slug}`}>
                    <a className={styles.action}>{post.title}</a>
                  </Link>
                </h2>
                <div>{post.date}</div>
              </div>
              <p>{post.description}</p>
            </section>
          ))}
        </div>
      </main>
    </>
  );
}
export const getStaticProps = async () => {
  const data = await getAllPublished();
  return {
    props: {
      posts: data,
    },
    revalidate: 60,
  };
};
