import Head from "next/head";
import { getAllPublished } from "../lib/notion";
import util from "../styles/util.module.css";
import PostTile from "../components/tiles/postTile";

//page header and in-page description
const description =
  "Search engine optimisaton and web development insight, guides, tools & other things that I like writing about.";

export default function Home({ posts }) {
  console.log(posts);
  if (!posts) return <h1>No posts</h1>;
  return (
    <>
      <Head>
        <title>Adam Durrant . Blog</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className={util.page} id='aboutPage'>
        <div className={util.pageColumn}>
          <h1 className={util.header}>Blog</h1>
          <p className={util.description}>{description}</p>
          {posts.map((post, index) => (
            <PostTile
              key={index}
              title={post.title}
              content={post.description}
              tags={post.tags}
              date={post.date}
              url={post.slug}
            />
          ))}
        </div>
      </main>
    </>
  );
}
export const getStaticProps = async () => {
  const data = await getAllPublished();
  return {
    props: {
      posts: data,
    },
    revalidate: 60,
  };
};
